---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cjw.
--- DateTime: 2022/10/24 17:47
---
--获取用户id和优惠卷id
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]

--库存key
local stockKey = "seckill:stock:" .. voucherId
--订单key
local orderKey = "seckill:order:" .. voucherId

--判断库存
local stock = redis.call("get", stockKey)
if (tonumber(stock) <= 0) then
    return 1
end


if (redis.call("sismember",orderKey,userId) == 1) then
    --已下单,返回2
    return 2
end



--未下单，扣减redis中的库存
redis.call("incrby",stockKey,-1)
--将用户下单的信息写入redis中
redis.call("sadd",orderKey,userId)

-- 3.6.发送消息到队列中， XADD stream.orders * k1 v1 k2 v2 ...
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)

--成功，返回0
return 0

